declare const _default: (() => {
    queueName?: string;
    logLevel?: "error" | "info" | "warn" | "trace" | "debug" | "fatal";
    pythonExecutable?: string;
    wrapperScriptPath?: string;
    maxConcurrentTasks?: number;
    processTimeoutMs?: number;
    gracefulShutdownMs?: number;
    pidCheckIntervalMs?: number;
    fileWatchTimeoutMs?: number;
    inactivityTimeoutMs?: number;
    wrapperWorkingDir?: string;
    redisHost?: string;
    redisPort?: number;
    redisPassword?: string;
    enableDetailedLogs?: boolean;
    sessionLogsDir?: string;
    awaitWriteFinish?: boolean;
    awaitWriteFinishMs?: number;
}) & import("node_modules/@nestjs/config").ConfigFactoryKeyHost<{
    queueName?: string;
    logLevel?: "error" | "info" | "warn" | "trace" | "debug" | "fatal";
    pythonExecutable?: string;
    wrapperScriptPath?: string;
    maxConcurrentTasks?: number;
    processTimeoutMs?: number;
    gracefulShutdownMs?: number;
    pidCheckIntervalMs?: number;
    fileWatchTimeoutMs?: number;
    inactivityTimeoutMs?: number;
    wrapperWorkingDir?: string;
    redisHost?: string;
    redisPort?: number;
    redisPassword?: string;
    enableDetailedLogs?: boolean;
    sessionLogsDir?: string;
    awaitWriteFinish?: boolean;
    awaitWriteFinishMs?: number;
}>;
export default _default;
