declare const _default: (() => {
    pythonExecutable?: string;
    wrapperScriptPath?: string;
    maxConcurrentTasks?: number;
    processTimeoutMs?: number;
    gracefulShutdownMs?: number;
    pidCheckIntervalMs?: number;
    fileWatchTimeoutMs?: number;
    inactivityTimeoutMs?: number;
    wrapperWorkingDir?: string;
    queueName?: string;
    redisHost?: string;
    redisPort?: number;
    redisPassword?: string;
    logLevel?: "fatal" | "error" | "warn" | "info" | "debug" | "trace";
    enableDetailedLogs?: boolean;
    sessionLogsDir?: string;
    awaitWriteFinish?: boolean;
    awaitWriteFinishMs?: number;
}) & import("@nestjs/config").ConfigFactoryKeyHost<{
    pythonExecutable?: string;
    wrapperScriptPath?: string;
    maxConcurrentTasks?: number;
    processTimeoutMs?: number;
    gracefulShutdownMs?: number;
    pidCheckIntervalMs?: number;
    fileWatchTimeoutMs?: number;
    inactivityTimeoutMs?: number;
    wrapperWorkingDir?: string;
    queueName?: string;
    redisHost?: string;
    redisPort?: number;
    redisPassword?: string;
    logLevel?: "fatal" | "error" | "warn" | "info" | "debug" | "trace";
    enableDetailedLogs?: boolean;
    sessionLogsDir?: string;
    awaitWriteFinish?: boolean;
    awaitWriteFinishMs?: number;
}>;
export default _default;
