version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: cc-task-manager-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cc_task_manager
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cc_task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cc-task-manager-network

  # Redis (for caching and queue management when enabled)
  redis:
    image: redis:7-alpine
    container_name: cc-task-manager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - cc-task-manager-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  cc-task-manager-network:
    driver: bridge